### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by gillesdami** [samvv/js-proxy-deep#2]
Hi,

I like your lib, however i'd like to have a very optimized deep proxy solution.
We could optimize you library by avoiding function re-declaration and few other ways.

For example this is the kind of patterns that i'd like to refactor:

```js
// slow
function a(v) {
  function b() {
    v()
  }

  b()
}

// fast
function b(v) {
  v()
}

function a(v) {
  b(v)
}
```

The function `createProxy` follow this pattern and refactoring it naively already improve the performances of the solution by 4 to 15 percents depending on the browser. (https://jsben.ch/wm6q8)

So my question is would you accept pull requests to optimize your code ?

**Comment by samvv** [comment]
Hi @gillesdami,

Too bad I missed your issue, because I'd be very interested in adding performance optimizations. Oddly enough, the benchmark you linked to doesn't show any performance improvement when tested in the latest release on Brave. Maybe the guys at V8 have been really busy? Anyways, when I have the time I'll be sure to add some benchmarks for further experimentation.

Regards,
Sam
